const assert = require('node:assert/strict');
const { test } = require('node:test');
const { entry, createHost, openDOM } = require('./helpers/body-webview');
const { overviewEntry } = require('./helpers/overview-entry');
const value = (ui, key) => ui.query('[data-overview-field="' + key + '"] .overview-value').textContent;

test('overview has Reqable groups, aligned rows, native collapse and no outer folding wrapper', async t => {
    const ui = await openDOM(t, createHost().main, [overviewEntry()]);
    ui.window.har.log.creator = { name: 'Reqable' };
    ui.click('.request-items [index="0"]', true);
    const overview = ui.query('.request-overview');
    assert.equal(overview.classList.contains('show'), true);
    assert.deepEqual(Array.from(overview.querySelectorAll('summary'), node => node.textContent), ['应用程序', '连接', '时间', '大小']);
    assert.equal(overview.querySelectorAll(':scope > details[open]').length, 4);
    assert.equal(overview.querySelectorAll('.overview-row').length, 31);
    assert.equal(overview.querySelectorAll('.data-table-column-resizer').length, 5);
    assert.equal(overview.querySelector('.inspector-section, .inspector-timing-bars'), null);
    assert.equal(ui.window.getComputedStyle(overview).overflow, 'auto');
    assert.equal(ui.window.getComputedStyle(overview.querySelector('.overview-row')).display, 'grid');
    assert.equal(value(ui, 'size.responseHeaders'), '250 B');
    assert.equal(value(ui, 'size.requestBody'), '0 B');
    const group = overview.querySelector('[data-overview-group="connection"]');
    ui.click('[data-overview-group="connection"] summary');
    assert.equal(group.open, false);
    assert.equal(overview.querySelector('[data-overview-group="timing"]').open, true);
    ui.click('[data-overview-group="connection"] summary');
    assert.equal(group.open, true);
    assert.equal(ui.query('.inspector-panel-url').textContent, ui.window.selectedReq.fullURL);
});

test('overview updates on selection, preserves collapsed groups and column widths, and never executes or redacts values', async t => {
    const item = overviewEntry();
    item._app.name = '<img src=x onerror="window.injected=1">secret-token-中😀';
    item._app.id = 'example.app.' + 'long'.repeat(60);
    const items = [item, entry()], original = JSON.stringify(items);
    const ui = await openDOM(t, createHost().main, items);
    ui.click('.request-items [index="0"]', true);
    assert.equal(value(ui, 'application.name'), item._app.name);
    assert.equal(value(ui, 'application.id'), item._app.id);
    assert.equal(ui.query('.request-overview img'), null);
    assert.equal(ui.window.injected, undefined);
    const table = ui.query('[data-overview-table]'), resizer = table.querySelector('.data-table-column-resizer');
    table.getBoundingClientRect = () => ({ left: 0, width: 600 });
    resizer.getBoundingClientRect = () => ({ left: (parseFloat(ui.query('.request-inspector').style.getPropertyValue('--overview-key-width')) || 180) - 4, width: 8 });
    resizer.dispatchEvent(new ui.window.KeyboardEvent('keydown', { key: 'ArrowRight', bubbles: true }));
    assert.equal(ui.query('.request-inspector').style.getPropertyValue('--overview-key-width'), '192px');
    resizer.dispatchEvent(new ui.window.MouseEvent('pointerdown', { clientX: 192, bubbles: true }));
    ui.window.dispatchEvent(new ui.window.MouseEvent('pointermove', { clientX: 232 }));
    ui.window.dispatchEvent(new ui.window.MouseEvent('pointercancel'));
    assert.equal(ui.query('.request-inspector').style.getPropertyValue('--overview-key-width'), '232px');
    assert.equal(ui.window.document.body.classList.contains('resizing-columns'), false);
    ui.click('[data-overview-group="connection"] summary');
    ui.click('.request-items [index="1"]');
    assert.equal(value(ui, 'application.name'), '—');
    assert.equal(value(ui, 'connection.clientPort'), '—');
    assert.equal(value(ui, 'timing.requestStart'), '—');
    assert.equal(ui.query('[data-overview-group="connection"]').open, false);
    assert.equal(ui.query('.request-inspector').style.getPropertyValue('--overview-key-width'), '232px');
    assert.equal(ui.query('.request-overview').querySelectorAll('.data-table-column-resizer').length, 5);
    ui.click('.request-panel .tab[name="请求体"]');
    assert.ok(ui.query('[data-body-source="request"] .cm-editor'));
    ui.click('.request-panel .tab[name="总览"]');
    assert.equal(ui.query('.request-overview').classList.contains('show'), true);
    assert.equal(JSON.stringify(ui.window.har.log.entries), original);
});
